### PR TITLE
Assign url value to InlineKeyboardButton in constructor.

### PR DESCRIPTION
**Pull request by a-a-k**
I saw that it was implemented earlier but I can't find a reason why it was removed. Could you merge it please?

### CODE REVIEW

**Comment by mhverbakel** [comment]
This change will not be backwards compatible **without recompiling the code**. To ensure backwards compatibility, add a new overload with a non-optional parameter.

**Comment by a-a-k** [comment]
@mhverbakel check it please.

**Comment by mhverbakel** [comment]
Are you sure this works? I believe that ctor(string, string) is now ambiguous... The last parameter shouldn't be optional if I'm not mistaking.

**Comment by a-a-k** [comment]
> The last parameter shouldn't be optional

It's not necessary. In this case `ctor(string, string)` the next ctor `public InlineKeyboardButton(string text, string callbackData = null)` will be executed.    
But you are right that `ctor(string, string)` is ambiguous for understanding. I've changed this. Check it please.

**Comment by mhverbakel** [comment]
You have my blessing!

**Pull request closed without merging**
