### PR TITLE
Master

### PR DESCRIPTION
**Pull request by MRACHINI**
Caption For Documents

### CODE REVIEW

**Comment by MrRoundRobin** [comment]
does it work? because it's not [documented](https://core.telegram.org/bots/api#senddocument)

**Comment by MRACHINI** [comment]
ya sure, i tried it on these channels:
https://telegram.me/TheSeriesChannel
https://telegram.me/TheMovieChannel

check them

**Comment by MRACHINI** [comment]
https://api.telegram.org/bot13245234523458:wertwertwertwertwert/sendDocument?chat_id=@TheMovieChannel&document=BQADBAADhgQAAnkG_QABba5ab5ID2EEC&caption=testCaption&performer=xxx

**Comment by MRACHINI** [comment]
make sure code is OK! please :)

**Pull request merged**
