### PR TITLE
Added new classes for InlineKeyboardButtons and made InlineKeyboardButton abstract

### PR DESCRIPTION
**Pull request by Olfi01**

### CODE REVIEW

**Comment by MrRoundRobin** [comment]
can you move the properties to the child classes

**Comment by Olfi01** [comment]
If you want... but in my opinion the class InlineKeyboardButton should still have all those because you maybe get to Deserialze one and don't wanna check the type, just get the properties, it'd be easier... plus, doing so could maybe meddle with JsonConvert

**Comment by MrRoundRobin** [comment]
that's possible, it's the same as the InlineQueryResults

**Comment by Olfi01** [comment]
okay, I'll take a look

**Pull request merged**
